import tempfile
import textwrap

from fpdf import FPDF


def generate_pdf(content):
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.set_margins(16, 16, 16)
    pdf.add_page()

    def clean_text(text):
        replacements = {
            "—": "-",
            "–": "-",
            "“": '"',
            "”": '"',
            "‘": "'",
            "’": "'",
            "•": "-",
            "✅": "",
            "🔍": "",
            "🧠": "",
            "✍️": "",
            "📊": "",
            "📄": "",
        }
        for old, new in replacements.items():
            text = text.replace(old, new)
        return text.encode("latin-1", "replace").decode("latin-1")

    def strip_markdown(text):
        text = text.replace("**", "").replace("__", "")
        text = text.replace("`", "")
        return text.strip()

    def write_wrapped(text, size=11, style="", color=(31, 41, 55), height=6):
        pdf.set_font("Helvetica", style=style, size=size)
        pdf.set_text_color(*color)

        wrapped_lines = textwrap.wrap(
            text,
            width=92,
            break_long_words=True,
            break_on_hyphens=False
        ) or [""]

        for wrapped_line in wrapped_lines:
            pdf.multi_cell(
                pdf.epw,
                height,
                wrapped_line,
                new_x="LMARGIN",
                new_y="NEXT"
            )

    def write_section_heading(text):
        pdf.ln(4)
        pdf.set_fill_color(236, 245, 255)
        pdf.set_draw_color(99, 179, 237)
        pdf.set_text_color(20, 83, 136)
        pdf.set_font("Helvetica", "B", 13)
        pdf.cell(pdf.epw, 9, strip_markdown(text), border="L", new_x="LMARGIN", new_y="NEXT", fill=True)
        pdf.ln(2)

    def write_table_row(line):
        cells = [strip_markdown(cell) for cell in line.strip("|").split("|")]
        if not any(cells):
            return

        pdf.set_fill_color(248, 250, 252)
        pdf.set_draw_color(226, 232, 240)
        pdf.set_text_color(51, 65, 85)
        pdf.set_font("Helvetica", size=9)

        column_width = pdf.epw / max(1, len(cells))
        row_height = 7
        start_x = pdf.get_x()
        start_y = pdf.get_y()
        max_lines = 1

        wrapped_cells = []
        for cell in cells:
            wrapped = textwrap.wrap(cell, width=max(12, int(70 / len(cells))), break_long_words=True) or [""]
            wrapped_cells.append(wrapped[:4])
            max_lines = max(max_lines, len(wrapped[:4]))

        actual_height = row_height * max_lines
        if pdf.get_y() + actual_height > pdf.page_break_trigger:
            pdf.add_page()
            start_x = pdf.get_x()
            start_y = pdf.get_y()

        for idx, wrapped in enumerate(wrapped_cells):
            pdf.set_xy(start_x + (idx * column_width), start_y)
            pdf.multi_cell(column_width, row_height, "\n".join(wrapped), border=1, align="L", fill=True)
        pdf.set_xy(start_x, start_y + actual_height)

    lines = [clean_text(line).replace("\t", "    ").strip() for line in content.split("\n")]
    title = next((strip_markdown(line.lstrip("# ").strip()) for line in lines if line.strip()), "Research Report")

    pdf.set_fill_color(8, 15, 28)
    pdf.rect(0, 0, 210, 34, style="F")
    pdf.set_text_color(226, 232, 240)
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_xy(16, 10)
    pdf.multi_cell(pdf.epw, 8, title[:90], new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(99, 179, 237)
    pdf.set_font("Helvetica", size=9)
    pdf.set_x(16)
    pdf.cell(pdf.epw, 6, "AI Research Report | Generated by ARES AI", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(12)

    for line in lines:
        clean_line = strip_markdown(line)

        if not clean_line:
            pdf.ln(3)
            continue

        if set(clean_line.replace("|", "").replace("-", "").replace(":", "").strip()) == set():
            continue

        if line.startswith("#"):
            heading = line.lstrip("#").strip()
            if strip_markdown(heading) != title:
                write_section_heading(heading)
            continue

        if line.startswith(("1.", "2.", "3.", "4.", "5.", "6.")):
            write_section_heading(clean_line)
            continue

        if line.startswith("|") and line.endswith("|"):
            write_table_row(line)
            continue

        if clean_line.startswith(("-", "*")):
            bullet = clean_line.lstrip("-* ").strip()
            write_wrapped(f"- {bullet}", size=10.5, color=(51, 65, 85), height=6)
            pdf.ln(1)
            continue

        write_wrapped(clean_line)
        pdf.ln(1)

    temp_file = tempfile.NamedTemporaryFile(
        delete=False,
        suffix=".pdf"
    )
    temp_file.close()

    pdf.output(temp_file.name)

    return temp_file.name
